### ISSUE TITLE
Add additional fields to CFP Reviewer view of presentations

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-drupal#86] opened 2023-07-18 22:30 UTC
opening this for @kcbraunschweig.

CFP Reviewers would like to be able to see the following additional views when logged in and looking at a presentation page:
- Title
- Short Abstract
- Long Abstract
- Message to reviewers
- Speaker name
- Comments

Today we only show a subset.

We don't want comments visible to the general unauthenticated public. Only people with the right role who are logged in.

**Comment by irabinovitch** [comment] 2023-07-18 22:42
@kcbraunschweig i think this is done.

**Comment by kcbraunschweig** [comment] 2023-08-04 03:35
I can only confirm this on 20x and only on talks that are unpublished but that is probably as intended. I think this looks good. Will reopen if it doesn't show up as expected once we have

**Comment by kcbraunschweig** [comment] 2023-08-04 03:36
This is weird, to try to test this I tried to create a test submission to the 21x cfp. 21x is in the drop down and was selected, however after submitting successfully it saves as:
https://www.socallinuxexpo.org/scale/19x/presentations/kc-test-1
Clearly under 19x. Not sure whats up with that. Also I can't use this to validate the change because its my submission so I see the owner view not the voter view.

**Comment by irabinovitch** [comment] 2023-08-05 06:20
@DrupalPhil thoughts?

**Comment by kcbraunschweig** [comment] 2023-08-28 17:02
I think what I hit was an example of https://github.com/socallinuxexpo/scale-drupal/issues/64
Gonna close this issue as the additional fields seem to be there which was the point of this issue.

**Closed** 2023-08-28 17:03 UTC
